[phases.setup]
aptPkgs = ["libglib2.0-0", "libsm6", "libxext6", "libxrender-dev"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "uvicorn fastapi_app:app --host 0.0.0.0 --port $PORT"